### ISSUE TITLE
Users report not getting a CSV download option once completing the checklist

### ISSUE THREAD

**Issue by alwalderman** [devopsguys/production-readiness-review#16]
Needs analysis and QA

**Comment by rswe** [comment]
waiting for detailed user feedback of the issue

**Comment by rswe** [comment]
user feedback: When Results page presented, Download CSV link not obviously visible. Usability issue
Solution: Add Details of how to download Results as CSV at top of Results page when displayed

**Comment by rswe** [comment]
Waiting for user feedback

**Comment by rswe** [comment]
user verified success
